name: build mnaddon
on:
    push:
        branches:
            - main
    workflow_dispatch: # 手动触发
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              with:
                  ref: 'main'
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '16.x'
            - name: Install dependencies
              run: yarn

            - name: Build mnaddon
              run: yarn build

            - name: Upload mnaddon
              uses: actions/upload-artifact@v2
              with:
                name: ohmymn.mnaddon
                path: ./dist/ohmymn.mnaddon